version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3300:3306'
    volumes:
      - './data:/var/lib/mysql'
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: 9mRE
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db

